/**
 * Runtime code generation
 * Generates runtime files for standalone server usage
 */

import type { ScannedResolver } from '../types'
import { relative } from 'pathe'

/**
 * Generate resolver module code
 * Outputs Nitro-compatible format with { resolver: ... } wrapper
 */
export function generateResolverModule(
  resolvers: ScannedResolver[],
  baseDir: string,
): string {
  if (!resolvers.length) {
    return `// Auto-generated by nitro-graphql - no resolvers found
export const resolvers = []
`
  }

  const imports: string[] = []
  const resolverEntries: string[] = []
  const reexports: string[] = []

  for (const resolver of resolvers) {
    // Calculate relative path from baseDir to resolver file
    const relativePath = relative(baseDir, resolver.specifier).replace(/\.ts$/, '')

    // Get all export names
    const exportNames = resolver.imports.map(i => i.name)

    if (exportNames.length > 0) {
      // Import statement
      imports.push(`import { ${exportNames.join(', ')} } from '${relativePath}'`)

      // Resolver entries with wrapper
      for (const name of exportNames) {
        resolverEntries.push(`  { resolver: ${name} }`)
      }

      // Re-export for tree-shaking
      reexports.push(`export { ${exportNames.join(', ')} } from '${relativePath}'`)
    }
  }

  return `// Auto-generated by nitro-graphql - do not edit
${imports.join('\n')}

export const resolvers = [
${resolverEntries.join(',\n')},
]

// Re-exports for tree-shaking
${reexports.join('\n')}
`
}

/**
 * Generate schema module code
 */
export function generateSchemaModule(schemaString: string): string {
  // Escape backticks in schema string
  const escapedSchema = schemaString.replace(/`/g, '\\`').replace(/\$/g, '\\$')

  return `// Auto-generated by nitro-graphql - do not edit
export const schemaString = \`
${escapedSchema}
\`

// Pre-parsed for convenience
import { parse } from 'graphql'
export const typeDefs = parse(schemaString)
`
}

/**
 * Generate runtime index module
 */
export function generateRuntimeIndex(): string {
  return `// Auto-generated by nitro-graphql - do not edit
export { resolvers } from './resolvers'
export { schemaString, typeDefs } from './schema'
`
}
