catalogMode: prefer

cleanupUnusedCatalogs: true

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playgrounds/*
  - crates/*

overrides:
  graphql: ^16.12.0
  vite: 8.0.0-beta.7

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@apollo/server': ^5.2.0
  '@apollo/subgraph': ^2.12.2
  '@bomb.sh/tab': ^0.0.11
  '@graphql-codegen/core': ^5.0.0
  '@graphql-codegen/import-types-preset': ^3.0.1
  '@graphql-codegen/typed-document-node': ^6.1.5
  '@graphql-codegen/typescript': ^5.0.7
  '@graphql-codegen/typescript-generic-sdk': ^4.1.0
  '@graphql-codegen/typescript-operations': ^5.0.7
  '@graphql-codegen/typescript-resolvers': ^5.1.5
  '@graphql-tools/graphql-file-loader': ^8.1.9
  '@graphql-tools/load': ^8.1.8
  '@graphql-tools/load-files': ^7.0.1
  '@graphql-tools/merge': ^9.1.7
  '@graphql-tools/schema': ^10.0.31
  '@graphql-tools/url-loader': ^9.0.6
  '@graphql-tools/utils': ^11.0.0
  '@napi-rs/cli': ^3.5.1
  '@nuxt/kit': https://pkg.pr.new/@nuxt/kit@33005
  '@nuxt/schema': https://pkg.pr.new/@nuxt/schema@33005
  '@tailwindcss/vite': ^4.1.18
  '@types/node': ^25.0.6
  '@types/ws': ^8.18.1
  '@vitejs/devtools': ^0.0.0-alpha.16
  '@vitejs/plugin-vue': ^6.0.3
  '@vitest/coverage-v8': ^4.0.17
  '@vitest/ui': ^4.0.17
  bumpp: ^10.3.2
  c12: ^3.3.3
  changelogen: ^0.6.2
  chokidar: ^5.0.0
  citty: ^0.1.6
  consola: ^3.4.2
  crossws: ^0.4.1
  defu: ^6.1.4
  eslint: ^9.39.2
  giget: ^2.0.0
  graphql: ^16.12.0
  graphql-config: ^5.1.5
  graphql-scalars: ^1.25.0
  graphql-sse: ^2.6.0
  graphql-ws: ^6.0.6
  graphql-yoga: 5.16.2
  knitwork: ^1.3.0
  mlly: ^1.8.0
  nitro: https://pkg.pr.new/nitrojs/nitro@99691fc
  nuxt: https://pkg.pr.new/nuxt@33005
  ofetch: ^2.0.0-alpha.3
  ohash: ^2.0.11
  oxc-parser: ^0.108.0
  pathe: ^2.0.3
  perfect-debounce: ^2.0.0
  srvx: ^0.10.0
  tailwindcss: ^4.1.18
  tinyglobby: ^0.2.15
  tsdown: ^0.19.0
  typescript: ^5.9.3
  vite: 8.0.0-beta.7
  vitepress-plugin-llms: ^1.10.0
  vitest: ^4.0.17
  vue: ^3.5.26
  vue-router: ^4.6.4
  ws: ^8.19.0
  zod: ^4.3.5

trustPolicyIgnoreAfter: 10.08
