/**
 * Template for GraphQL subscription client
 * Uses crossws for cross-platform WebSocket support
 * Supports both native WebSocket and SSE (via WebSocketSSE)
 *
 * Features:
 * - Default: Each subscription gets its own connection
 * - Opt-in multiplexing: Use createSession() to share a connection
 */

export const subscribeClientTemplate = `// This file is auto-generated by nitro-graphql for GraphQL subscriptions
// Uses crossws for cross-platform WebSocket and SSE support
// You can modify this file according to your needs
//
// Usage Examples:
// ---------------
// Basic subscription (dedicated connection per subscription):
//   const sub = subscriptionClient.subscribe(query, variables, onData, onError)
//   sub.unsubscribe()
//
// Multiplexed subscriptions (shared connection via session):
//   const session = subscriptionClient.createSession()
//   const sub1 = session.subscribe(query1, vars1, onData1)
//   const sub2 = session.subscribe(query2, vars2, onData2)
//   // Both use the same WebSocket connection
//   sub1.unsubscribe() // Connection stays open for sub2
//   sub2.unsubscribe() // Connection closes (no more subscriptions)
//   // Or close all at once:
//   session.close()
//
// With authentication (connectionParams):
//   const authClient = createSubscriptionClient({
//     connectionParams: () => ({
//       authorization: \`Bearer \${getToken()}\`,
//       userId: getCurrentUserId(),
//     })
//   })

import WebSocket from 'crossws/websocket'
import { WebSocketSSE } from 'crossws/websocket/sse'

// ============================================================================
// Types
// ============================================================================

export type ConnectionState = 'idle' | 'connecting' | 'connected' | 'reconnecting' | 'disconnected' | 'error'

export interface SubscriptionOptions<TVariables = Record<string, unknown>> {
  query: string
  variables?: TVariables
  onData?: (data: unknown) => void
  onError?: (error: Error) => void
  onConnected?: () => void
  onReconnected?: () => void
  onDisconnected?: () => void
  onRetrying?: (attempt: number, maxAttempts: number) => void
  onMaxRetriesReached?: () => void
  onStateChange?: (state: ConnectionState) => void
  maxRetries?: number
  connectionTimeoutMs?: number
  connectionParams?: Record<string, unknown>
}

export interface SubscriptionHandle {
  unsubscribe: () => void
  readonly isConnected: boolean
  readonly state: ConnectionState
  readonly id: string
}

export type SubscriptionTransport = 'websocket' | 'sse' | 'auto'

// ============================================================================
// Constants
// ============================================================================

const DEFAULT_CONNECTION_TIMEOUT_MS = 10000
const DEFAULT_MAX_RETRIES = 5
const MAX_BACKOFF_MS = 30000
const DEFAULT_PING_INTERVAL_MS = 25000
const DEFAULT_PONG_TIMEOUT_MS = 5000

// ============================================================================
// GraphQL-WS Protocol
// ============================================================================

interface GraphQLWSMessage {
  id?: string
  type: string
  payload?: unknown
}

// ============================================================================
// Dedicated Connection (one subscription per connection)
// ============================================================================

function createDedicatedSubscription<TData = unknown, TVariables = Record<string, unknown>>(
  endpoint: string,
  options: SubscriptionOptions<TVariables>,
  transport: 'websocket' | 'sse',
): SubscriptionHandle {
  let ws: WebSocket | InstanceType<typeof WebSocketSSE> | null = null
  let isConnected = false
  let connectionState: ConnectionState = 'idle'
  let retryCount = 0
  let subscriptionId: string | null = null
  let intentionalClose = false
  let hasConnectedBefore = false
  let reconnectTimeout: ReturnType<typeof setTimeout> | null = null
  let connectionTimeout: ReturnType<typeof setTimeout> | null = null
  let pingInterval: ReturnType<typeof setInterval> | null = null
  let pongTimeout: ReturnType<typeof setTimeout> | null = null
  let messageIdCounter = 0

  const maxRetries = options.maxRetries ?? DEFAULT_MAX_RETRIES
  const connectionTimeoutMs = options.connectionTimeoutMs ?? DEFAULT_CONNECTION_TIMEOUT_MS
  const id = String(Date.now()) + '-' + Math.random().toString(36).substr(2, 9)

  function setState(state: ConnectionState) {
    connectionState = state
    options.onStateChange?.(state)
  }

  function startPing() {
    stopPing()
    pingInterval = setInterval(() => {
      if (!isConnected) return
      sendMessage({ type: 'ping' })
      pongTimeout = setTimeout(() => {
        options.onError?.(new Error('Server not responding to ping'))
        cleanupConnection()
        scheduleReconnect()
      }, DEFAULT_PONG_TIMEOUT_MS)
    }, DEFAULT_PING_INTERVAL_MS)
  }

  function stopPing() {
    if (pingInterval) { clearInterval(pingInterval); pingInterval = null }
    if (pongTimeout) { clearTimeout(pongTimeout); pongTimeout = null }
  }

  function connect() {
    if (typeof window === 'undefined' && typeof globalThis.WebSocket === 'undefined') return
    if (reconnectTimeout) { clearTimeout(reconnectTimeout); reconnectTimeout = null }
    cleanupConnection()
    setState('connecting')

    if (transport === 'sse') {
      const url = new URL(endpoint, typeof window !== 'undefined' ? window.location.origin : 'http://localhost')
      url.searchParams.set('query', options.query)
      if (options.variables) url.searchParams.set('variables', JSON.stringify(options.variables))
      ws = new WebSocketSSE(url.toString(), { bidir: true, stream: true })
    } else {
      const wsUrl = endpoint.replace(/^http/, 'ws')
      ws = new WebSocket(wsUrl, 'graphql-transport-ws')
    }

    ws.onopen = () => {
      if (transport === 'websocket') {
        connectionTimeout = setTimeout(() => {
          options.onError?.(new Error('Connection timeout'))
          setState('error')
          cleanupConnection()
          scheduleReconnect()
        }, connectionTimeoutMs)
        sendMessage({ type: 'connection_init', payload: options.connectionParams || {} })
      } else {
        isConnected = true
        retryCount = 0
        setState('connected')
        options.onConnected?.()
      }
    }

    ws.onmessage = (event: MessageEvent) => {
      const data = typeof event.data === 'string' ? event.data : String(event.data)
      if (transport === 'sse') {
        handleSSEMessage(data)
      } else {
        handleWebSocketMessage(data)
      }
    }

    ws.onerror = () => {
      options.onError?.(new Error(\`\${transport === 'websocket' ? 'WebSocket' : 'SSE'} connection error\`))
    }

    ws.onclose = () => {
      isConnected = false
      subscriptionId = null
      if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null }
      options.onDisconnected?.()
      if (intentionalClose) { intentionalClose = false; setState('disconnected'); return }
      scheduleReconnect()
    }
  }

  function handleSSEMessage(data: string) {
    try {
      const response = JSON.parse(data) as { data?: Record<string, unknown>; errors?: Array<{ message: string }> }
      if (response.errors?.length) {
        options.onError?.(new Error(response.errors[0]?.message || 'GraphQL Error'))
      } else if (response.data) {
        options.onData?.(Object.values(response.data)[0] as TData)
      }
    } catch {}
  }

  function handleWebSocketMessage(data: string) {
    try {
      const message: GraphQLWSMessage = JSON.parse(data)
      switch (message.type) {
        case 'connection_ack':
          if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null }
          isConnected = true
          retryCount = 0
          setState('connected')
          if (hasConnectedBefore) { options.onReconnected?.() } else { hasConnectedBefore = true; options.onConnected?.() }
          startPing()
          subscribe()
          break
        case 'connection_error':
          if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null }
          const errPayload = message.payload as { message?: string } | undefined
          options.onError?.(new Error(errPayload?.message || 'Connection rejected'))
          setState('error')
          break
        case 'next':
          if (message.payload && typeof message.payload === 'object') {
            const payload = message.payload as { data?: unknown; errors?: Array<{ message: string }> }
            if (payload.errors) { options.onError?.(new Error(payload.errors[0]?.message || 'GraphQL Error')) }
            else if (payload.data) { options.onData?.(Object.values(payload.data as Record<string, unknown>)[0] as TData) }
          }
          break
        case 'error':
          if (Array.isArray(message.payload)) {
            options.onError?.(new Error((message.payload as Array<{ message: string }>)[0]?.message || 'Subscription error'))
          }
          break
        case 'complete':
          subscriptionId = null
          break
        case 'ping':
          sendMessage({ type: 'pong' })
          break
        case 'pong':
          if (pongTimeout) { clearTimeout(pongTimeout); pongTimeout = null }
          break
      }
    } catch (e) {
      options.onError?.(e instanceof Error ? e : new Error('Failed to parse message'))
    }
  }

  function scheduleReconnect() {
    if (reconnectTimeout) { clearTimeout(reconnectTimeout); reconnectTimeout = null }
    if (retryCount < maxRetries) {
      retryCount++
      setState('reconnecting')
      options.onRetrying?.(retryCount, maxRetries)
      const delay = Math.min(1000 * Math.pow(2, retryCount), MAX_BACKOFF_MS) + Math.random() * 1000
      reconnectTimeout = setTimeout(connect, delay)
    } else {
      setState('error')
      options.onMaxRetriesReached?.()
      options.onError?.(new Error('Max reconnection attempts reached'))
    }
  }

  function sendMessage(message: GraphQLWSMessage) {
    if (ws && ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(message))
  }

  function subscribe() {
    subscriptionId = String(++messageIdCounter)
    sendMessage({ id: subscriptionId, type: 'subscribe', payload: { query: options.query, variables: options.variables } })
  }

  function cleanupConnection() {
    stopPing()
    if (ws) {
      if (subscriptionId) sendMessage({ id: subscriptionId, type: 'complete' })
      ws.close()
      ws = null
      isConnected = false
      subscriptionId = null
    }
  }

  function disconnect() {
    intentionalClose = true
    stopPing()
    if (reconnectTimeout) { clearTimeout(reconnectTimeout); reconnectTimeout = null }
    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null }
    cleanupConnection()
    setState('disconnected')
  }

  connect()

  return {
    unsubscribe: disconnect,
    get isConnected() { return isConnected },
    get state() { return connectionState },
    id,
  }
}

// ============================================================================
// Session (multiplexed connection)
// ============================================================================

interface SubscriptionEntry {
  id: string
  query: string
  variables?: Record<string, unknown>
  onData?: (data: unknown) => void
  onError?: (error: Error) => void
  onConnected?: () => void
  onReconnected?: () => void
  onDisconnected?: () => void
  onRetrying?: (attempt: number, maxAttempts: number) => void
  onMaxRetriesReached?: () => void
  onStateChange?: (state: ConnectionState) => void
  hasNotifiedConnect: boolean
}

export interface SubscriptionSession {
  subscribe<TData = unknown, TVariables = Record<string, unknown>>(
    query: string,
    variables?: TVariables,
    onData?: (data: TData) => void,
    onError?: (error: Error) => void,
  ): SubscriptionHandle
  readonly state: ConnectionState
  readonly isConnected: boolean
  readonly subscriptionCount: number
  close(): void
}

function createSession(
  endpoint: string,
  connectionParams: Record<string, unknown>,
  maxRetries: number,
  connectionTimeoutMs: number,
): SubscriptionSession {
  let ws: WebSocket | null = null
  let connectionState: ConnectionState = 'idle'
  let retryCount = 0
  let hasConnectedBefore = false
  let intentionalClose = false
  let reconnectTimeout: ReturnType<typeof setTimeout> | null = null
  let connectionTimeout: ReturnType<typeof setTimeout> | null = null
  let pingInterval: ReturnType<typeof setInterval> | null = null
  let pongTimeout: ReturnType<typeof setTimeout> | null = null

  const subscriptions = new Map<string, SubscriptionEntry>()
  const pendingSubscriptions: SubscriptionEntry[] = []
  let messageIdCounter = 0

  function setState(state: ConnectionState) {
    connectionState = state
    for (const sub of subscriptions.values()) sub.onStateChange?.(state)
  }

  function generateId(): string { return String(++messageIdCounter) }

  function connect(): void {
    if (connectionState === 'connected' || connectionState === 'connecting') return
    if (typeof window === 'undefined' && typeof globalThis.WebSocket === 'undefined') return
    if (reconnectTimeout) { clearTimeout(reconnectTimeout); reconnectTimeout = null }

    setState('connecting')
    const wsUrl = endpoint.replace(/^http/, 'ws')
    ws = new WebSocket(wsUrl, 'graphql-transport-ws')

    ws.onopen = () => {
      connectionTimeout = setTimeout(() => {
        notifyAllError(new Error('Connection timeout'))
        setState('error')
        cleanupConnection()
        scheduleReconnect()
      }, connectionTimeoutMs)
      sendMessage({ type: 'connection_init', payload: connectionParams })
    }

    ws.onmessage = (event: MessageEvent) => {
      handleMessage(typeof event.data === 'string' ? event.data : String(event.data))
    }

    ws.onerror = () => notifyAllError(new Error('WebSocket connection error'))

    ws.onclose = () => {
      if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null }
      for (const sub of subscriptions.values()) sub.onDisconnected?.()
      if (intentionalClose) { intentionalClose = false; setState('disconnected'); return }
      scheduleReconnect()
    }
  }

  function handleMessage(data: string) {
    try {
      const message: GraphQLWSMessage = JSON.parse(data)
      switch (message.type) {
        case 'connection_ack':
          if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null }
          retryCount = 0
          setState('connected')
          startPing()
          const isReconnect = hasConnectedBefore
          hasConnectedBefore = true
          for (const sub of pendingSubscriptions) subscribeInternal(sub)
          pendingSubscriptions.length = 0
          if (isReconnect) {
            for (const sub of subscriptions.values()) { sub.onReconnected?.(); sendSubscribe(sub) }
          } else {
            for (const sub of subscriptions.values()) {
              if (!sub.hasNotifiedConnect) { sub.hasNotifiedConnect = true; sub.onConnected?.() }
            }
          }
          break
        case 'connection_error':
          if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null }
          notifyAllError(new Error((message.payload as { message?: string })?.message || 'Connection rejected'))
          setState('error')
          break
        case 'next':
          if (message.id) {
            const sub = subscriptions.get(message.id)
            if (sub && message.payload && typeof message.payload === 'object') {
              const payload = message.payload as { data?: unknown; errors?: Array<{ message: string }> }
              if (payload.errors) sub.onError?.(new Error(payload.errors[0]?.message || 'GraphQL Error'))
              else if (payload.data) sub.onData?.(Object.values(payload.data as Record<string, unknown>)[0])
            }
          }
          break
        case 'error':
          if (message.id) {
            const sub = subscriptions.get(message.id)
            if (sub && Array.isArray(message.payload)) {
              sub.onError?.(new Error((message.payload as Array<{ message: string }>)[0]?.message || 'Subscription error'))
            }
          }
          break
        case 'complete':
          if (message.id) subscriptions.delete(message.id)
          break
        case 'ping':
          sendMessage({ type: 'pong' })
          break
        case 'pong':
          if (pongTimeout) { clearTimeout(pongTimeout); pongTimeout = null }
          break
      }
    } catch (e) {
      notifyAllError(e instanceof Error ? e : new Error('Failed to parse message'))
    }
  }

  function notifyAllError(error: Error) {
    for (const sub of subscriptions.values()) sub.onError?.(error)
  }

  function startPing() {
    stopPing()
    pingInterval = setInterval(() => {
      if (connectionState !== 'connected') return
      sendMessage({ type: 'ping' })
      pongTimeout = setTimeout(() => {
        notifyAllError(new Error('Server not responding to ping'))
        cleanupConnection()
        scheduleReconnect()
      }, DEFAULT_PONG_TIMEOUT_MS)
    }, DEFAULT_PING_INTERVAL_MS)
  }

  function stopPing() {
    if (pingInterval) { clearInterval(pingInterval); pingInterval = null }
    if (pongTimeout) { clearTimeout(pongTimeout); pongTimeout = null }
  }

  function scheduleReconnect() {
    if (reconnectTimeout) { clearTimeout(reconnectTimeout); reconnectTimeout = null }
    if (retryCount < maxRetries) {
      retryCount++
      setState('reconnecting')
      for (const sub of subscriptions.values()) sub.onRetrying?.(retryCount, maxRetries)
      const delay = Math.min(1000 * Math.pow(2, retryCount), MAX_BACKOFF_MS) + Math.random() * 1000
      reconnectTimeout = setTimeout(() => connect(), delay)
    } else {
      setState('error')
      for (const sub of subscriptions.values()) {
        sub.onMaxRetriesReached?.()
        sub.onError?.(new Error('Max reconnection attempts reached'))
      }
    }
  }

  function sendMessage(message: GraphQLWSMessage) {
    if (ws && ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(message))
  }

  function sendSubscribe(sub: SubscriptionEntry) {
    sendMessage({ id: sub.id, type: 'subscribe', payload: { query: sub.query, variables: sub.variables } })
  }

  function subscribeInternal(sub: SubscriptionEntry): void {
    subscriptions.set(sub.id, sub)
    if (connectionState === 'connected') {
      sendSubscribe(sub)
      if (!sub.hasNotifiedConnect) { sub.hasNotifiedConnect = true; sub.onConnected?.() }
    }
  }

  function unsubscribe(id: string): void {
    const sub = subscriptions.get(id)
    if (sub) {
      if (connectionState === 'connected') sendMessage({ id, type: 'complete' })
      subscriptions.delete(id)
    }
    const pendingIdx = pendingSubscriptions.findIndex(s => s.id === id)
    if (pendingIdx !== -1) pendingSubscriptions.splice(pendingIdx, 1)
    if (subscriptions.size === 0 && pendingSubscriptions.length === 0) close()
  }

  function cleanupConnection() {
    stopPing()
    if (ws) { ws.close(); ws = null }
  }

  function close(): void {
    intentionalClose = true
    stopPing()
    if (reconnectTimeout) { clearTimeout(reconnectTimeout); reconnectTimeout = null }
    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null }
    if (connectionState === 'connected') {
      for (const sub of subscriptions.values()) sendMessage({ id: sub.id, type: 'complete' })
    }
    subscriptions.clear()
    pendingSubscriptions.length = 0
    cleanupConnection()
    setState('disconnected')
  }

  return {
    subscribe<TData = unknown, TVariables = Record<string, unknown>>(
      query: string,
      variables?: TVariables,
      onData?: (data: TData) => void,
      onError?: (error: Error) => void,
    ): SubscriptionHandle {
      const id = generateId()
      const entry: SubscriptionEntry = {
        id, query, variables,
        onData: onData as (data: unknown) => void,
        onError,
        hasNotifiedConnect: false,
      }

      if (connectionState === 'connected') {
        subscribeInternal(entry)
      } else {
        pendingSubscriptions.push(entry)
        connect()
      }

      return {
        unsubscribe: () => unsubscribe(id),
        get isConnected() { return connectionState === 'connected' },
        get state() { return connectionState },
        id,
      }
    },
    get state() { return connectionState },
    get isConnected() { return connectionState === 'connected' },
    get subscriptionCount() { return subscriptions.size },
    close,
  }
}

// ============================================================================
// Subscription Client Factory
// ============================================================================

export interface SubscriptionClientConfig {
  wsEndpoint?: string
  httpEndpoint?: string
  transport?: SubscriptionTransport
  connectionParams?: Record<string, unknown> | (() => Record<string, unknown> | Promise<Record<string, unknown>>)
  connectionTimeoutMs?: number
  maxRetries?: number
}

export function createSubscriptionClient(config: SubscriptionClientConfig = {}) {
  const wsEndpoint = config.wsEndpoint ?? '/api/graphql/ws'
  const httpEndpoint = config.httpEndpoint ?? '/api/graphql'
  const configTransport = config.transport ?? 'auto'
  const configConnectionParams = config.connectionParams
  const connectionTimeoutMs = config.connectionTimeoutMs ?? DEFAULT_CONNECTION_TIMEOUT_MS
  const maxRetries = config.maxRetries ?? DEFAULT_MAX_RETRIES

  function getTransport(): 'websocket' | 'sse' {
    if (configTransport === 'websocket') return 'websocket'
    if (configTransport === 'sse') return 'sse'
    return 'websocket'
  }

  function getConnectionParams(): Record<string, unknown> {
    if (!configConnectionParams) return {}
    if (typeof configConnectionParams === 'function') {
      const result = configConnectionParams()
      if (result instanceof Promise) {
        console.warn('[nitro-graphql] Async connectionParams not supported in subscribe(), use subscribeAsync()')
        return {}
      }
      return result
    }
    return configConnectionParams
  }

  return {
    /**
     * Subscribe with a dedicated connection (default behavior)
     */
    subscribe<TData = unknown, TVariables = Record<string, unknown>>(
      query: string,
      variables?: TVariables,
      onData?: (data: TData) => void,
      onError?: (error: Error) => void,
    ): SubscriptionHandle {
      const transport = getTransport()
      const endpoint = transport === 'websocket' ? wsEndpoint : httpEndpoint
      return createDedicatedSubscription<TData, TVariables>(
        endpoint,
        { query, variables, onData: onData as (data: unknown) => void, onError, connectionParams: getConnectionParams(), connectionTimeoutMs, maxRetries },
        transport,
      )
    },

    /**
     * Subscribe with full options (dedicated connection)
     */
    async subscribeAsync<TData = unknown, TVariables = Record<string, unknown>>(
      options: SubscriptionOptions<TVariables> & { transport?: SubscriptionTransport },
    ): Promise<SubscriptionHandle> {
      const transport = options.transport ?? getTransport()
      const endpoint = transport === 'websocket' ? wsEndpoint : httpEndpoint

      let connectionParams = options.connectionParams
      if (!connectionParams && configConnectionParams) {
        connectionParams = typeof configConnectionParams === 'function' ? await configConnectionParams() : configConnectionParams
      }

      return createDedicatedSubscription<TData, TVariables>(
        endpoint,
        { ...options, connectionParams, connectionTimeoutMs: options.connectionTimeoutMs ?? connectionTimeoutMs, maxRetries: options.maxRetries ?? maxRetries },
        transport,
      )
    },

    /**
     * Create a multiplexed session - all subscriptions share one connection
     */
    createSession(): SubscriptionSession {
      const transport = getTransport()
      if (transport === 'sse') {
        console.warn('[nitro-graphql] SSE does not support multiplexing, falling back to dedicated connections')
      }
      return createSession(wsEndpoint, getConnectionParams(), maxRetries, connectionTimeoutMs)
    },
  }
}

// Default client instance
export const subscriptionClient = createSubscriptionClient()
`
