/**
 * Template for GraphQL subscription client
 * Supports both WebSocket (graphql-ws) and SSE (Server-Sent Events) transports
 */

export const subscribeClientTemplate = `// This file is auto-generated by nitro-graphql for GraphQL subscriptions
// Supports both WebSocket (graphql-ws protocol) and SSE (Server-Sent Events)
// You can modify this file according to your needs

// ============================================================================
// Common Types
// ============================================================================

export interface SubscriptionOptions<TVariables = Record<string, unknown>> {
  /** GraphQL subscription query string */
  query: string
  /** Variables for the subscription */
  variables?: TVariables
  /** Callback when data is received */
  onData?: (data: unknown) => void
  /** Callback when an error occurs */
  onError?: (error: Error) => void
  /** Callback when connection is established */
  onConnected?: () => void
  /** Callback when connection is closed */
  onDisconnected?: () => void
  /** Maximum number of reconnection attempts (default: 5) */
  maxRetries?: number
  /** Custom headers for the request */
  headers?: Record<string, string>
}

export interface SubscriptionClient {
  /** Unsubscribe and close the connection */
  unsubscribe: () => void
  /** Current connection state */
  readonly isConnected: boolean
}

// ============================================================================
// WebSocket Transport (graphql-ws protocol)
// ============================================================================

interface GraphQLWSMessage {
  id?: string
  type: string
  payload?: unknown
}

let wsMessageId = 0

/**
 * Create a GraphQL subscription using WebSocket (graphql-ws protocol)
 * Compatible with graphql-yoga and apollo-server WebSocket handlers
 */
export function createWSSubscription<TData = unknown, TVariables = Record<string, unknown>>(
  endpoint: string,
  options: SubscriptionOptions<TVariables>,
): SubscriptionClient {
  let ws: WebSocket | null = null
  let isConnected = false
  let retryCount = 0
  let subscriptionId: string | null = null
  const maxRetries = options.maxRetries ?? 5

  function connect() {
    if (typeof window === 'undefined') {
      // SSR - don't connect
      return
    }

    // Convert HTTP URL to WebSocket URL
    const wsUrl = endpoint.replace(/^http/, 'ws')

    // Close existing connection
    disconnect()

    ws = new WebSocket(wsUrl, 'graphql-transport-ws')

    ws.onopen = () => {
      // Send connection_init
      sendMessage({ type: 'connection_init' })
    }

    ws.onmessage = (event) => {
      try {
        const message: GraphQLWSMessage = JSON.parse(event.data)
        handleMessage(message)
      } catch (e) {
        options.onError?.(e instanceof Error ? e : new Error('Failed to parse WebSocket message'))
      }
    }

    ws.onerror = () => {
      options.onError?.(new Error('WebSocket error'))
    }

    ws.onclose = () => {
      isConnected = false
      subscriptionId = null
      options.onDisconnected?.()

      // Reconnect with exponential backoff
      if (retryCount < maxRetries) {
        retryCount++
        const delay = Math.min(1000 * Math.pow(2, retryCount), 30000)
        setTimeout(connect, delay)
      } else {
        options.onError?.(new Error('Max reconnection attempts reached'))
      }
    }
  }

  function sendMessage(message: GraphQLWSMessage) {
    if (ws && ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(message))
    }
  }

  function handleMessage(message: GraphQLWSMessage) {
    switch (message.type) {
      case 'connection_ack':
        isConnected = true
        retryCount = 0
        options.onConnected?.()
        // Now subscribe
        subscribe()
        break

      case 'next':
        if (message.payload && typeof message.payload === 'object') {
          const payload = message.payload as { data?: unknown; errors?: Array<{ message: string }> }
          if (payload.errors) {
            options.onError?.(new Error(payload.errors[0]?.message || 'GraphQL Error'))
          } else if (payload.data) {
            // Extract first field from data (the subscription field)
            const subscriptionData = Object.values(payload.data as Record<string, unknown>)[0]
            options.onData?.(subscriptionData as TData)
          }
        }
        break

      case 'error':
        if (message.payload && Array.isArray(message.payload)) {
          const errors = message.payload as Array<{ message: string }>
          options.onError?.(new Error(errors[0]?.message || 'Subscription error'))
        }
        break

      case 'complete':
        // Subscription completed by server
        subscriptionId = null
        break

      case 'ping':
        sendMessage({ type: 'pong' })
        break
    }
  }

  function subscribe() {
    subscriptionId = String(++wsMessageId)
    sendMessage({
      id: subscriptionId,
      type: 'subscribe',
      payload: {
        query: options.query,
        variables: options.variables,
      },
    })
  }

  function disconnect() {
    if (ws) {
      if (subscriptionId) {
        sendMessage({ id: subscriptionId, type: 'complete' })
      }
      ws.close()
      ws = null
      isConnected = false
      subscriptionId = null
    }
  }

  // Start connection
  connect()

  return {
    unsubscribe: disconnect,
    get isConnected() {
      return isConnected
    },
  }
}

// ============================================================================
// SSE Transport (Server-Sent Events)
// ============================================================================

/**
 * Create a GraphQL subscription using Server-Sent Events (SSE)
 * Compatible with GraphQL Yoga's SSE subscription mode
 */
export function createSSESubscription<TData = unknown, TVariables = Record<string, unknown>>(
  endpoint: string,
  options: SubscriptionOptions<TVariables>,
): SubscriptionClient {
  let eventSource: EventSource | null = null
  let isConnected = false
  let retryCount = 0
  const maxRetries = options.maxRetries ?? 5

  function connect() {
    if (typeof window === 'undefined') {
      // SSR - don't connect
      return
    }

    // Build URL with query parameters
    const url = new URL(endpoint, window.location.origin)
    url.searchParams.set('query', options.query)
    if (options.variables) {
      url.searchParams.set('variables', JSON.stringify(options.variables))
    }

    // Close existing connection
    disconnect()

    eventSource = new EventSource(url.toString())

    eventSource.onopen = () => {
      isConnected = true
      retryCount = 0
      options.onConnected?.()
    }

    // GraphQL Yoga sends 'next' events for subscription data
    eventSource.addEventListener('next', (event: MessageEvent) => {
      try {
        const response = JSON.parse(event.data)
        if (response.errors) {
          options.onError?.(new Error(response.errors[0]?.message || 'GraphQL Error'))
        } else if (response.data) {
          // Extract first field from data (the subscription field)
          const subscriptionData = Object.values(response.data)[0]
          options.onData?.(subscriptionData as TData)
        }
      } catch (e) {
        options.onError?.(e instanceof Error ? e : new Error('Failed to parse subscription data'))
      }
    })

    // Also handle generic message event
    eventSource.onmessage = (event) => {
      try {
        const response = JSON.parse(event.data)
        if (response.data) {
          const subscriptionData = Object.values(response.data)[0]
          options.onData?.(subscriptionData as TData)
        }
      } catch {
        // Ignore parse errors for non-JSON messages
      }
    }

    eventSource.onerror = () => {
      isConnected = false
      options.onDisconnected?.()

      // Reconnect with exponential backoff
      if (retryCount < maxRetries) {
        retryCount++
        const delay = Math.min(1000 * Math.pow(2, retryCount), 30000)
        setTimeout(connect, delay)
      } else {
        options.onError?.(new Error('Max reconnection attempts reached'))
      }
    }
  }

  function disconnect() {
    if (eventSource) {
      eventSource.close()
      eventSource = null
      isConnected = false
    }
  }

  // Start connection
  connect()

  return {
    unsubscribe: disconnect,
    get isConnected() {
      return isConnected
    },
  }
}

// ============================================================================
// Unified Subscription Client
// ============================================================================

export type SubscriptionTransport = 'websocket' | 'sse' | 'auto'

export interface SubscriptionClientConfig {
  /** HTTP endpoint for GraphQL (used for SSE and as base for WebSocket) */
  httpEndpoint?: string
  /** WebSocket endpoint for GraphQL subscriptions */
  wsEndpoint?: string
  /** Transport to use: 'websocket', 'sse', or 'auto' (default: 'auto') */
  transport?: SubscriptionTransport
}

/**
 * Create a unified subscription client that supports both WebSocket and SSE
 */
export function createSubscriptionClient(config: SubscriptionClientConfig = {}) {
  const httpEndpoint = config.httpEndpoint ?? '/api/graphql'
  const wsEndpoint = config.wsEndpoint ?? '/api/graphql/ws'
  const transport = config.transport ?? 'auto'

  function getTransport(): 'websocket' | 'sse' {
    if (transport === 'websocket') return 'websocket'
    if (transport === 'sse') return 'sse'

    // Auto-detect: prefer WebSocket if available
    if (typeof WebSocket !== 'undefined') {
      return 'websocket'
    }
    return 'sse'
  }

  return {
    /**
     * Subscribe to a GraphQL subscription
     */
    subscribe<TData = unknown, TVariables = Record<string, unknown>>(
      query: string,
      variables?: TVariables,
      onData?: (data: TData) => void,
      onError?: (error: Error) => void,
    ): SubscriptionClient {
      const selectedTransport = getTransport()

      if (selectedTransport === 'websocket') {
        return createWSSubscription<TData, TVariables>(wsEndpoint, {
          query,
          variables,
          onData: onData as (data: unknown) => void,
          onError,
        })
      }

      return createSSESubscription<TData, TVariables>(httpEndpoint, {
        query,
        variables,
        onData: onData as (data: unknown) => void,
        onError,
      })
    },

    /**
     * Subscribe with full options
     */
    subscribeWithOptions<TData = unknown, TVariables = Record<string, unknown>>(
      options: SubscriptionOptions<TVariables> & { transport?: SubscriptionTransport },
    ): SubscriptionClient {
      const selectedTransport = options.transport ?? getTransport()

      if (selectedTransport === 'websocket') {
        return createWSSubscription<TData, TVariables>(wsEndpoint, options)
      }

      return createSSESubscription<TData, TVariables>(httpEndpoint, options)
    },
  }
}

// Default client instance
export const subscriptionClient = createSubscriptionClient()

// Re-export for convenience
export { createWSSubscription as createWebSocketSubscription }
export { createSSESubscription as createServerSentEventsSubscription }
`
