// This file is auto-generated by nitro-graphql for GraphQL subscriptions
// Uses crossws for cross-platform WebSocket and SSE support
// You can modify this file according to your needs

import WebSocket from 'crossws/websocket'
import { WebSocketSSE } from 'crossws/websocket/sse'

// ============================================================================
// Types
// ============================================================================

export interface SubscriptionOptions<TVariables = Record<string, unknown>> {
  /** GraphQL subscription query string */
  query: string
  /** Variables for the subscription */
  variables?: TVariables
  /** Callback when data is received */
  onData?: (data: unknown) => void
  /** Callback when an error occurs */
  onError?: (error: Error) => void
  /** Callback when connection is established */
  onConnected?: () => void
  /** Callback when connection is closed */
  onDisconnected?: () => void
  /** Maximum number of reconnection attempts (default: 5) */
  maxRetries?: number
}

export interface SubscriptionClient {
  /** Unsubscribe and close the connection */
  unsubscribe: () => void
  /** Current connection state */
  readonly isConnected: boolean
}

export type SubscriptionTransport = 'websocket' | 'sse' | 'auto'

// ============================================================================
// GraphQL-WS Protocol Implementation
// ============================================================================

interface GraphQLWSMessage {
  id?: string
  type: string
  payload?: unknown
}

let messageId = 0

/**
 * Create a GraphQL subscription
 * Uses graphql-ws protocol over WebSocket or SSE (via WebSocketSSE)
 */
export function createSubscription<TData = unknown, TVariables = Record<string, unknown>>(
  endpoint: string,
  options: SubscriptionOptions<TVariables>,
  transport: 'websocket' | 'sse' = 'websocket',
): SubscriptionClient {
  let ws: WebSocket | InstanceType<typeof WebSocketSSE> | null = null
  let isConnected = false
  let retryCount = 0
  let subscriptionId: string | null = null
  const maxRetries = options.maxRetries ?? 5

  function connect() {
    if (typeof window === 'undefined' && typeof globalThis.WebSocket === 'undefined') {
      // SSR without WebSocket support - skip
      return
    }

    // Close existing connection
    disconnect()

    if (transport === 'sse') {
      // Use WebSocketSSE for SSE transport
      // Build URL with query parameters for SSE
      const url = new URL(endpoint, typeof window !== 'undefined' ? window.location.origin : 'http://localhost')
      url.searchParams.set('query', options.query)
      if (options.variables) {
        url.searchParams.set('variables', JSON.stringify(options.variables))
      }

      ws = new WebSocketSSE(url.toString(), {
        bidir: true,
        stream: true,
      })
    }
    else {
      // Use native WebSocket
      const wsUrl = endpoint.replace(/^http/, 'ws')
      ws = new WebSocket(wsUrl, 'graphql-transport-ws')
    }

    ws.onopen = () => {
      if (transport === 'websocket') {
        // Send connection_init for WebSocket
        sendMessage({ type: 'connection_init' })
      }
      else {
        // SSE doesn't need handshake, directly connected
        isConnected = true
        retryCount = 0
        options.onConnected?.()
      }
    }

    ws.onmessage = (event: MessageEvent) => {
      try {
        const data = typeof event.data === 'string' ? event.data : String(event.data)
        const message: GraphQLWSMessage = JSON.parse(data)
        handleMessage(message)
      }
      catch (e) {
        // For SSE, try to parse as GraphQL response directly
        if (transport === 'sse') {
          try {
            const data = typeof event.data === 'string' ? event.data : String(event.data)
            const response = JSON.parse(data)
            if (response.data) {
              const subscriptionData = Object.values(response.data)[0]
              options.onData?.(subscriptionData as TData)
            }
            else if (response.errors) {
              options.onError?.(new Error(response.errors[0]?.message || 'GraphQL Error'))
            }
          }
          catch {
            // Ignore parse errors
          }
        }
        else {
          options.onError?.(e instanceof Error ? e : new Error('Failed to parse message'))
        }
      }
    }

    ws.onerror = () => {
      options.onError?.(new Error(`${transport === 'websocket' ? 'WebSocket' : 'SSE'} connection error`))
    }

    ws.onclose = () => {
      isConnected = false
      subscriptionId = null
      options.onDisconnected?.()

      // Reconnect with exponential backoff
      if (retryCount < maxRetries) {
        retryCount++
        const delay = Math.min(1000 * 2 ** retryCount, 30000)
        setTimeout(connect, delay)
      }
      else {
        options.onError?.(new Error('Max reconnection attempts reached'))
      }
    }
  }

  function sendMessage(message: GraphQLWSMessage) {
    if (ws && ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(message))
    }
  }

  function handleMessage(message: GraphQLWSMessage) {
    switch (message.type) {
      case 'connection_ack':
        isConnected = true
        retryCount = 0
        options.onConnected?.()
        // Subscribe after connection acknowledged
        subscribe()
        break

      case 'next':
        if (message.payload && typeof message.payload === 'object') {
          const payload = message.payload as { data?: unknown, errors?: Array<{ message: string }> }
          if (payload.errors) {
            options.onError?.(new Error(payload.errors[0]?.message || 'GraphQL Error'))
          }
          else if (payload.data) {
            const subscriptionData = Object.values(payload.data as Record<string, unknown>)[0]
            options.onData?.(subscriptionData as TData)
          }
        }
        break

      case 'error':
        if (message.payload && Array.isArray(message.payload)) {
          const errors = message.payload as Array<{ message: string }>
          options.onError?.(new Error(errors[0]?.message || 'Subscription error'))
        }
        break

      case 'complete':
        subscriptionId = null
        break

      case 'ping':
        sendMessage({ type: 'pong' })
        break
    }
  }

  function subscribe() {
    subscriptionId = String(++messageId)
    sendMessage({
      id: subscriptionId,
      type: 'subscribe',
      payload: {
        query: options.query,
        variables: options.variables,
      },
    })
  }

  function disconnect() {
    if (ws) {
      if (subscriptionId) {
        sendMessage({ id: subscriptionId, type: 'complete' })
      }
      ws.close()
      ws = null
      isConnected = false
      subscriptionId = null
    }
  }

  // Start connection
  connect()

  return {
    unsubscribe: disconnect,
    get isConnected() {
      return isConnected
    },
  }
}

// ============================================================================
// Subscription Client Factory
// ============================================================================

export interface SubscriptionClientConfig {
  /** WebSocket endpoint for subscriptions (default: '/api/graphql/ws') */
  wsEndpoint?: string
  /** HTTP endpoint for SSE subscriptions (default: '/api/graphql') */
  httpEndpoint?: string
  /** Transport to use: 'websocket', 'sse', or 'auto' (default: 'auto') */
  transport?: SubscriptionTransport
}

/**
 * Create a subscription client factory
 */
export function createSubscriptionClient(config: SubscriptionClientConfig = {}) {
  const wsEndpoint = config.wsEndpoint ?? '/api/graphql/ws'
  const httpEndpoint = config.httpEndpoint ?? '/api/graphql'
  const configTransport = config.transport ?? 'auto'

  function getTransport(): 'websocket' | 'sse' {
    if (configTransport === 'websocket')
      return 'websocket'
    if (configTransport === 'sse')
      return 'sse'
    // Auto: prefer WebSocket
    return 'websocket'
  }

  return {
    /**
     * Subscribe to a GraphQL subscription
     */
    subscribe<TData = unknown, TVariables = Record<string, unknown>>(
      query: string,
      variables?: TVariables,
      onData?: (data: TData) => void,
      onError?: (error: Error) => void,
    ): SubscriptionClient {
      const transport = getTransport()
      const endpoint = transport === 'websocket' ? wsEndpoint : httpEndpoint

      return createSubscription<TData, TVariables>(
        endpoint,
        {
          query,
          variables,
          onData: onData as (data: unknown) => void,
          onError,
        },
        transport,
      )
    },

    /**
     * Subscribe with full options
     */
    subscribeWithOptions<TData = unknown, TVariables = Record<string, unknown>>(
      options: SubscriptionOptions<TVariables> & { transport?: SubscriptionTransport },
    ): SubscriptionClient {
      const transport = options.transport ?? getTransport()
      const endpoint = transport === 'websocket' ? wsEndpoint : httpEndpoint

      return createSubscription<TData, TVariables>(endpoint, options, transport)
    },
  }
}

// Default client instance
export const subscriptionClient = createSubscriptionClient()
