catalog:
  '@types/node': ^22.10.2
  dayjs: ^1.11.19
  gray-matter: ^4.0.3
  gsap: ^3.13.0
  mermaid: ^11.12.1
  shiki: ^3.15.0
  tsx: ^4.19.2
  vitepress: 2.0.0-alpha.13
  vitepress-plugin-mermaid: ^2.0.17
