import type { Nitro } from 'nitropack'
import type { NitroGraphQLOptions } from './types'
import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { mergeTypeDefs } from '@graphql-tools/merge'
import { makeExecutableSchema } from '@graphql-tools/schema'
import { watch } from 'chokidar'
import { consola } from 'consola'
import { join } from 'pathe'
import { setupClientWatcher } from './client-watcher'
import { generateTypes } from './codegen'
import { scanGraphQLFiles } from './scanner'
import { debounce } from './utils'

const logger = consola.withTag('graphql')

// Type generation function that can be called from hooks
async function regenerateGraphQLTypes(nitro: Nitro) {
  try {
    // Scan all GraphQL files and resolvers
    const scanResult = await scanGraphQLFiles(nitro)

    if (scanResult.typeDefs.length === 0) {
      logger.warn('⚠️  No schema files found')
      return
    }

    // Merge all type definitions
    const mergedTypeDefs = mergeTypeDefs(scanResult.typeDefs)

    // Create schema
    const schema = makeExecutableSchema({
      typeDefs: mergedTypeDefs,
      resolvers: {}, // Empty resolvers for type generation
    })

    // Generate types using dynamic import
    const generatedTypes = await generateTypes(schema)

    // Write to file
    const outputPath = join(nitro.options.buildDir, 'types', 'graphql-types.generated.ts')
    const typesDir = join(nitro.options.buildDir, 'types')
    await mkdir(typesDir, { recursive: true })
    await writeFile(outputPath, generatedTypes)

    // Update graphql.d.ts
    const graphqlDtsPath = join(typesDir, 'graphql.d.ts')
    const graphqlDtsContent = `// Auto-generated by nitro-graphql
import type { Resolvers as Test } from './graphql-types.generated'

declare module 'nitro-graphql' {
  interface Resolvers extends Test {}
}
`
    await writeFile(graphqlDtsPath, graphqlDtsContent)

    logger.success('✨ Types regenerated')
  }
  catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error)
    logger.error('❌ Type generation failed:', errorMessage)
  }
}

export function devmode(nitro: Nitro, options: NitroGraphQLOptions) {
  // Setup file watchers in dev mode - completely excluded from production
  if (nitro.options.dev) {
    // Setup GraphQL watcher using our own chokidar instance
    const generateTypesDebounced = debounce(async () => {
      await regenerateGraphQLTypes(nitro)
    }, 300)

    // Setup GraphQL file watcher
    const graphqlDir = join(nitro.options.srcDir, 'graphql')

    logger.info('🔍 Setting up independent GraphQL watcher for directory:', graphqlDir)

    // Check if the GraphQL directory exists
    try {
      // const { existsSync } = await import('node:fs')
      if (!existsSync(graphqlDir)) {
        logger.warn(`⚠️ GraphQL directory not found: ${graphqlDir}`)
        return
      }
    }
    catch (error) {
      logger.warn('⚠️ Could not check GraphQL directory:', error)
      return
    }

    const graphqlWatcher = watch(graphqlDir, {
      ignoreInitial: true,
      persistent: true,
      usePolling: true, // Enable polling for better compatibility on macOS
      interval: 500, // Poll every 500ms
      depth: 10, // Watch subdirectories
    })

    // Set up event handlers
    graphqlWatcher.on('add', (path) => {
      logger.info('📁 GraphQL file added:', path)
      generateTypesDebounced()
    })

    graphqlWatcher.on('change', (path) => {
      logger.info('📝 GraphQL file changed:', path)
      generateTypesDebounced()
    })

    graphqlWatcher.on('unlink', (path) => {
      logger.info('🗑️ GraphQL file deleted:', path)
      generateTypesDebounced()
    })

    graphqlWatcher.on('error', (error) => {
      logger.error('❌ GraphQL watcher error:', error)
    })

    // Handle raw events as fallback for better macOS compatibility
    graphqlWatcher.on('raw', (event, path) => {
      // Check for directory changes that indicate GraphQL file modifications
      if (event === 'change' && path && path.endsWith('graphql')) {
        logger.info('📝 GraphQL directory change detected, regenerating types')
        generateTypesDebounced()
      }
    })

    graphqlWatcher.on('ready', () => {
      logger.success('✅ GraphQL file watcher ready')
    })

    // Close watcher when Nitro closes
    nitro.hooks.hook('close', async () => {
      await graphqlWatcher.close()
      logger.info('🔒 GraphQL watcher closed')
    })

    setupClientWatcher(nitro, options)

    logger.success('✅ Independent GraphQL watcher set up')
  }
}
