import type { Nitro } from 'nitropack/types'
import type { NitroGraphQLYogaOptions } from './types'
import { mkdir, writeFile } from 'node:fs/promises'
import { mergeTypeDefs } from '@graphql-tools/merge'
import { makeExecutableSchema } from '@graphql-tools/schema'
import { consola } from 'consola'
import { defineNitroModule } from 'nitropack/kit'
import { join } from 'pathe'
import { generateTypes } from './codegen'
import { scanGraphQLFiles } from './scanner'
import { setupGraphQLWatcher } from './watcher'

export default defineNitroModule({
  name: 'nitro:graphql-yoga',
  async setup(nitro: Nitro) {
    // Get module options from nitro config
    const options: NitroGraphQLYogaOptions = {
      endpoint: '/api/graphql',
      playground: true,
      cors: false,
      cacheHeaders: {
        enabled: true,
        maxAge: 604800, // 1 week
      },
      // Merge with user config from nitro.options
      ...(nitro.options as any).graphqlYoga,
      // Fallback to runtimeConfig for backward compatibility
      ...nitro.options.runtimeConfig?.graphqlYoga,
    }
    // Add GraphQL path to known chunk prefixes
    const graphqlPath = join(nitro.options.srcDir, 'graphql')

    // Access the internal rollup config and add our prefix
    nitro.hooks.hook('rollup:before', (nitro, rollupConfig) => {
      // Add GraphQL path to chunkNamePrefixes
      const originalChunkFileNames = rollupConfig.output.chunkFileNames
      rollupConfig.output.chunkFileNames = (chunk) => {
        // Only GraphQL resolvers (actual resolver files) should go to graphql folder
        const allIds = chunk.moduleIds || []

        const hasGraphQLResolverFile = allIds.some(id =>
          // Only server/graphql resolver files (not node_modules, not virtual modules)
          id.includes(graphqlPath)
          && !id.includes('node_modules')
          && !id.includes('#nitro-graphql-yoga')
          && (id.endsWith('.ts') || id.endsWith('.js') || id.endsWith('.mjs')),
        )

        if (hasGraphQLResolverFile) {
          return `chunks/graphql/[name].mjs`
        }
        // Use original logic for other chunks
        if (typeof originalChunkFileNames === 'function') {
          return originalChunkFileNames(chunk)
        }
        return originalChunkFileNames || 'chunks/_/[name].mjs'
      }
    })

    // Add virtual imports
    nitro.options.virtual ??= {}

    // Add context type
    nitro.options.virtual['#nitro-graphql-yoga/context'] = () => `
export type { GraphQLContext } from 'nitro-graphql-yoga/context'
`

    // Initial scan
    const scanResult = await scanGraphQLFiles(nitro)

    // Log resolver discovery for debugging
    if (scanResult.resolvers.length > 0) {
      consola.success(`[graphql] Found ${scanResult.resolvers.length} resolvers`)

      if (nitro.options.dev) {
        consola.info('[graphql] Resolver files:')
        for (const resolver of scanResult.resolvers) {
          consola.info(`  ${resolver.name} -> ${resolver.relativePath}`)
        }
      }
    }

    // Generate initial types if we have GraphQL files
    if (scanResult.typeDefs.length > 0) {
      const mergedTypeDefs = mergeTypeDefs(scanResult.typeDefs)
      const schema = makeExecutableSchema({
        typeDefs: mergedTypeDefs,
        resolvers: {},
      })

      const generatedTypes = await generateTypes(schema)

      // Write to file
      const outputPath = join(nitro.options.buildDir, 'types', 'graphql-types.generated.ts')
      const typesDir = join(nitro.options.buildDir, 'types')
      await mkdir(typesDir, { recursive: true })
      await writeFile(outputPath, generatedTypes)

      // Create graphql.d.ts that declares the module
      const graphqlDtsPath = join(typesDir, 'graphql.d.ts')
      const graphqlDtsContent = `// Auto-generated by nitro-graphql-yoga
import type { Resolvers as Test } from './graphql-types.generated'

declare module 'nitro-graphql-yoga' {
  interface Resolvers extends Test {}
}
`
      await writeFile(graphqlDtsPath, graphqlDtsContent)

      consola.success('[graphql] Generated types at:', outputPath)
    }

    // Setup file watcher in dev mode
    if (nitro.options.dev) {
      await setupGraphQLWatcher(nitro)
    }

    // Add GraphQL Yoga handlers
    nitro.options.handlers = nitro.options.handlers || []
    const endpoint = options.endpoint || '/api/graphql'

    // Main GraphQL endpoint
    nitro.options.handlers.push({
      route: endpoint,
      handler: '#nitro-graphql-yoga/handler',
      method: 'get',
    })

    nitro.options.handlers.push({
      route: endpoint,
      handler: '#nitro-graphql-yoga/handler',
      method: 'post',
    })

    nitro.options.handlers.push({
      route: endpoint,
      handler: '#nitro-graphql-yoga/handler',
      method: 'options',
    })

    // Health check endpoint
    nitro.options.handlers.push({
      route: `${endpoint}/health`,
      handler: '#nitro-graphql-yoga/health',
      method: 'get',
    })

    // Create GraphQL handler
    nitro.options.virtual['#nitro-graphql-yoga/handler'] = () => `
import { createYoga } from 'graphql-yoga'
import { defineEventHandler, readRawBody, setHeader, setResponseStatus } from 'h3'
import { useStorage } from 'nitro/runtime'
import { makeExecutableSchema } from '@graphql-tools/schema'
import { mergeTypeDefs, mergeResolvers } from '@graphql-tools/merge'
import { loadFilesSync } from '@graphql-tools/load-files'
import { join } from 'pathe'
// Types are generated at build time to .nitro/graphql-types.generated.ts

// GraphQL Context type is injected via context module

// Create resolver helper
globalThis.createResolver = function(resolvers) {
  return resolvers
}

// Dynamic schema loading function
async function loadTypeDefs() {
  const schemaPath = join('${nitro.options.srcDir}', 'graphql', '**', '*.graphql')
  const { loadFilesSync } = await import('@graphql-tools/load-files')
  return loadFilesSync(schemaPath, {
    recursive: true,
  })
}

// Load resolvers using dynamic imports (Nitro handles the bundling)
const resolverImports = [
${scanResult.resolvers.map(resolver => `  () => import('${resolver.path}')`).join(',\n')}
]

// Async function to load resolvers
async function loadResolvers() {
  let resolvers = {}
  try {
    if (resolverImports.length > 0) {
      const resolverModules = []
      
      for (let i = 0; i < resolverImports.length; i++) {
        try {
          const resolverModule = await resolverImports[i]()
          const resolver = resolverModule.default || resolverModule
          
          if (resolver) {
            resolverModules.push(resolver)
            console.log('[nitro-graphql-yoga] Loaded resolver:', i)
          }
        } catch (error) {
          console.warn('[nitro-graphql-yoga] Failed to load resolver:', i, error.message)
        }
      }
      
      if (resolverModules.length > 0) {
        resolvers = mergeResolvers(resolverModules)
        console.log('[nitro-graphql-yoga] Successfully merged', resolverModules.length, 'resolvers')
      } else {
        console.warn('[nitro-graphql-yoga] No resolvers could be loaded')
        resolvers = { Query: {}, Mutation: {} }
      }
    } else {
      console.warn('[nitro-graphql-yoga] No resolvers found')
      resolvers = { Query: {}, Mutation: {} }
    }
  } catch (error) {
    console.warn('[nitro-graphql-yoga] Error loading resolvers:', error.message)
    resolvers = { Query: {}, Mutation: {} }
  }
  return resolvers
}

// Apollo Sandbox HTML with 1 week cache
const apolloSandboxHtml = \`<!DOCTYPE html>
<html lang="en">
<body style="margin: 0; overflow-x: hidden; overflow-y: hidden">
<div id="sandbox" style="height:100vh; width:100vw;"></div>
<script src="https://embeddable-sandbox.cdn.apollographql.com/02e2da0fccbe0240ef03d2396d6c98559bab5b06/embeddable-sandbox.umd.production.min.js"></script>
<script>
new window.EmbeddedSandbox({
  target: "#sandbox",
  initialEndpoint: window.location.href,
  hideCookieToggle: false,
  initialState: {
    includeCookies: true
  }
});
</script>
</body>
</html>\`

// Set cache headers for Apollo Sandbox HTML (1 week = 604800 seconds)
function setApolloSandboxCacheHeaders(event) {
  setHeader(event, 'Cache-Control', 'public, max-age=604800, s-maxage=604800')
  setHeader(event, 'Expires', new Date(Date.now() + 604800000).toUTCString())
  setHeader(event, 'ETag', \`"apollo-sandbox-\${Date.now()}"\`)
}

// Lazy initialization
let yoga = null
let initPromise = null

async function getYoga() {
  // In development mode, always reload schema for hot updates
  const isDev = ${nitro.options.dev}
  if (yoga && !isDev) return yoga
  
  if (!initPromise || isDev) {
    // Reset yoga instance in development mode
    if (isDev) {
      yoga = null
    }
    
    initPromise = (async () => {
      const resolvers = await loadResolvers()
      const typeDefs = await loadTypeDefs()
      
      // Merge schema and resolvers
      const schema = makeExecutableSchema({
        typeDefs: mergeTypeDefs(typeDefs),
        resolvers,
      })

      yoga = createYoga({
        schema,
        context: async ({ request }) => {
          const event = request.$$event
          return {
            event,
            request,
            storage: useStorage(),
          }
        },
        graphqlEndpoint: '${endpoint}',
        graphiql: ${options.playground !== false},
        renderGraphiQL: () => apolloSandboxHtml,
        landingPage: false,
        cors: ${JSON.stringify(options.cors || false)},
      })
      
      return yoga
    })()
  }
  
  return initPromise
}

export default defineEventHandler(async (event) => {
  const { req } = event.node
  const host = req.headers.host || 'localhost'
  const protocol = 'http'
  const url = new URL(req.url || '/', protocol + '://' + host)
  
  // Attach event to request for context
  req.$$event = event
  
  const yogaInstance = await getYoga()
  const response = await yogaInstance.fetch(url.toString(), {
    method: req.method || 'GET',
    headers: req.headers,
    body: req.method !== 'GET' && req.method !== 'HEAD' ? await readRawBody(event) : undefined,
  }, {
    event,
  })
  
  // Set response headers
  response.headers.forEach((value, key) => {
    setHeader(event, key, value)
  })
  
  // Set status code
  setResponseStatus(event, response.status)
  
  // Return response body
  if (response.body) {
    const contentType = response.headers.get('content-type')
    if (contentType?.includes('text/html')) {
      // Set cache headers for Apollo Sandbox HTML
      setApolloSandboxCacheHeaders(event)
      return await response.text()
    }
    if (contentType?.includes('application/json')) {
      return await response.text()
    }
    return response.body
  }
  
  return null
})
`

    // Health check handler
    nitro.options.virtual['#nitro-graphql-yoga/health'] = () => `
import { defineEventHandler, setResponseStatus } from 'h3'

export default defineEventHandler(async (event) => {
  try {
    const response = await $fetch('${endpoint}', {
      method: 'POST',
      body: {
        query: 'query Health { __typename }',
        operationName: 'Health',
      },
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
    })
    
    if (response && typeof response === 'object' && 'data' in response) {
      return {
        status: 'healthy',
        message: 'GraphQL server is running',
        timestamp: new Date().toISOString(),
      }
    }
    
    throw new Error('Invalid response from GraphQL server')
  } catch (error) {
    setResponseStatus(event, 503)
    return {
      status: 'unhealthy',
      message: error.message || 'GraphQL server is not responding',
      timestamp: new Date().toISOString(),
    }
  }
})
`

    // Auto-import utilities
    if (nitro.options.imports) {
      nitro.options.imports.presets.push({
        from: 'nitro-graphql-yoga',
        imports: [
          'createResolver',
          'defineGraphQLResolver',
          'defineGraphQLSchema',
          'defineGraphQLResolvers',
          'gql',
        ],
      })
    }

    // Add TypeScript path alias for IDE support
    nitro.options.typescript ??= {} as any
    nitro.options.typescript.tsConfig ??= {}
    nitro.options.typescript.tsConfig.compilerOptions ??= {}
    nitro.options.typescript.tsConfig.compilerOptions.paths ??= {}
    nitro.options.typescript.tsConfig.compilerOptions.paths['#build/graphql-types.generated'] = [
      join(nitro.options.buildDir, 'types', 'graphql-types.generated.ts'),
    ]
    nitro.options.typescript.tsConfig.include = nitro.options.typescript.tsConfig.include || []
    nitro.options.typescript.tsConfig.include.push(
      join(nitro.options.buildDir, 'types', 'graphql-types.generated.ts'),
      join(nitro.options.buildDir, 'types', 'graphql.d.ts'),
    )
  },
})

export * from './codegen'
export * from './context'
export * from './types'
export { createResolver, defineGraphQLResolver } from './utils'
