import type { Nitro } from 'nitropack/types'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { mergeTypeDefs } from '@graphql-tools/merge'
import { makeExecutableSchema } from '@graphql-tools/schema'
import { watch } from 'chokidar'
import { consola } from 'consola'
import { generateTypes } from './codegen'
import { scanGraphQLFiles } from './scanner'
import { debounce } from './utils'

export async function setupGraphQLWatcher(nitro: Nitro) {
  // Use Nitro's scan pattern (like API route watching)
  const watchPatterns = nitro.options.scanDirs.flatMap(dir => [
    join(dir, 'graphql', '**/*.graphql'),
    join(dir, 'graphql', '**/*.gql'),
    join(dir, 'graphql', '**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}'),
  ])

  const currentTypeDefs: string[] = []
  let isGenerating = false

  const generateTypesDebounced = debounce(async () => {
    if (isGenerating)
      return
    isGenerating = true

    try {
      // Scan all GraphQL files and resolvers
      const scanResult = await scanGraphQLFiles(nitro)

      if (scanResult.typeDefs.length === 0) {
        console.log('[nitro-graphql-yoga] No GraphQL files found')
        return
      }

      // Log resolver updates
      if (scanResult.resolvers.length > 0) {
        consola.success(`[nitro-graphql-yoga] Updated ${scanResult.resolvers.length} resolver files`)
      }

      // Merge all type definitions
      const mergedTypeDefs = mergeTypeDefs(scanResult.typeDefs)

      // Create schema
      const schema = makeExecutableSchema({
        typeDefs: mergedTypeDefs,
        resolvers: {}, // Empty resolvers for type generation
      })

      // Generate types
      const generatedTypes = await generateTypes(schema)

      // Write to file
      const outputPath = join(nitro.options.buildDir, 'types', 'graphql-types.generated.ts')
      const typesDir = join(nitro.options.buildDir, 'types')
      await mkdir(typesDir, { recursive: true })
      await writeFile(outputPath, generatedTypes)

      // Update graphql.d.ts
      const graphqlDtsPath = join(typesDir, 'graphql.d.ts')
      const graphqlDtsContent = `// Auto-generated by nitro-graphql-yoga
import type { Resolvers as Test } from './graphql-types.generated'

declare module 'nitro-graphql-yoga' {
  interface Resolvers extends Test {}
}
`
      await writeFile(graphqlDtsPath, graphqlDtsContent)

      consola.success('[nitro-graphql-yoga] Types regenerated at:', outputPath)
    }
    catch (error) {
      console.error('[nitro-graphql-yoga] Error generating types:', error)
    }
    finally {
      isGenerating = false
    }
  }, 300)

  // Watch GraphQL files (like Nitro watches API routes)
  const watcher = watch(watchPatterns, {
    persistent: true,
    ignoreInitial: false,
    depth: 10,
    ignored: nitro.options.ignore || [],
  })

  watcher.on('add', generateTypesDebounced)
  watcher.on('change', generateTypesDebounced)
  watcher.on('unlink', generateTypesDebounced)

  // Clean up on close
  nitro.hooks.hook('close', () => {
    watcher.close()
  })

  console.log('[nitro-graphql-yoga] Watching GraphQL files for changes...')
}
