import type { Nitro } from 'nitropack/types'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { mergeTypeDefs } from '@graphql-tools/merge'
import { makeExecutableSchema } from '@graphql-tools/schema'
import { consola } from 'consola'
// import { generateTypes } from './codegen' // Conditionally imported to prevent bundling
import { scanGraphQLFiles } from './scanner'
import { debounce } from './utils'

const logger = consola.withTag('graphql')

// Type generation function that can be called from hooks
async function regenerateGraphQLTypes(nitro: Nitro) {
  try {
    // Scan all GraphQL files and resolvers
    const scanResult = await scanGraphQLFiles(nitro)

    if (scanResult.typeDefs.length === 0) {
      logger.warn('⚠️  No schema files found')
      return
    }

    // Merge all type definitions
    const mergedTypeDefs = mergeTypeDefs(scanResult.typeDefs)

    // Create schema
    const schema = makeExecutableSchema({
      typeDefs: mergedTypeDefs,
      resolvers: {}, // Empty resolvers for type generation
    })

    // Generate types using dynamic import
    const { generateTypes } = await import('./codegen')
    const generatedTypes = await generateTypes(schema)

    // Write to file
    const outputPath = join(nitro.options.buildDir, 'types', 'graphql-types.generated.ts')
    const typesDir = join(nitro.options.buildDir, 'types')
    await mkdir(typesDir, { recursive: true })
    await writeFile(outputPath, generatedTypes)

    // Update graphql.d.ts
    const graphqlDtsPath = join(typesDir, 'graphql.d.ts')
    const graphqlDtsContent = `// Auto-generated by nitro-graphql
import type { Resolvers as Test } from './graphql-types.generated'

declare module 'nitro-graphql' {
  interface Resolvers extends Test {}
}
`
    await writeFile(graphqlDtsPath, graphqlDtsContent)

    // Types updated silently
  }
  catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error)
    logger.error('❌ Type generation failed:', errorMessage)
  }
}

export async function setupGraphQLWatcher(nitro: Nitro) {
  // Use chokidar directly for reliable file watching
  const watchPatterns = nitro.options.scanDirs.flatMap(dir => [
    join(dir, 'graphql', '**/*.graphql'),
    join(dir, 'graphql', '**/*.gql'),
    join(dir, 'graphql', '**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}'),
  ])

  // Setup file watcher

  // Create debounced function for type generation
  const generateTypesDebounced = debounce(async () => {
    // Regenerate types silently
    await regenerateGraphQLTypes(nitro)
  }, 300)

  // Use chokidar for reliable file watching with specific files
  const { watch } = await import('chokidar')

  // Watch specific existing files instead of patterns for better reliability
  const existingFiles = await Promise.all(nitro.options.scanDirs.map(async (scanDir) => {
    const { glob } = await import('tinyglobby')
    const graphqlDir = join(scanDir, 'graphql')
    return glob([
      join(graphqlDir, '**/*.graphql'),
      join(graphqlDir, '**/*.gql'),
      join(graphqlDir, '**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}'),
    ], { absolute: true })
  })).then(results => results.flat())

  // File watching setup complete

  const watcher = watch(existingFiles.length > 0 ? existingFiles : watchPatterns, {
    persistent: true,
    ignoreInitial: true,
    ignored: /(^|[/\\])\../, // ignore dotfiles
    followSymlinks: false,
    depth: 10,
    usePolling: true, // Enable polling for better compatibility
    interval: 1000, // Check every second
    binaryInterval: 1000,
  })

  // watcher.on('ready', () => {})

  watcher.on('change', (_path) => {
    generateTypesDebounced()
  })

  watcher.on('add', (_path) => {
    generateTypesDebounced()
  })

  watcher.on('unlink', (_path) => {
    generateTypesDebounced()
  })

  watcher.on('error', (error) => {
    const errorMessage = error instanceof Error ? error.message : String(error)
    logger.error('❌ Watcher error:', errorMessage)
  })

  // Hook into Nitro's lifecycle to clean up watcher
  nitro.hooks.hook('close', () => {
    watcher.close()
  })

  // Also try to hook into Nitro's dev:reload for additional triggering
  nitro.hooks.hook('dev:reload', () => {
    generateTypesDebounced()
  })

  logger.success('✅ Watcher ready')
}
