import type { Nitro } from 'nitropack/types'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { mergeTypeDefs } from '@graphql-tools/merge'
import { makeExecutableSchema } from '@graphql-tools/schema'
import { consola } from 'consola'
import { generateTypes } from './codegen'
import { scanGraphQLFiles } from './scanner'
import { debounce } from './utils'

// Type generation function that can be called from hooks
async function regenerateGraphQLTypes(nitro: Nitro) {
  try {
    // Scan all GraphQL files and resolvers
    const scanResult = await scanGraphQLFiles(nitro)

    if (scanResult.typeDefs.length === 0) {
      consola.warn('[graphql] ⚠️  No schema files found')
      return
    }

    // Merge all type definitions
    const mergedTypeDefs = mergeTypeDefs(scanResult.typeDefs)

    // Create schema
    const schema = makeExecutableSchema({
      typeDefs: mergedTypeDefs,
      resolvers: {}, // Empty resolvers for type generation
    })

    // Generate types
    const generatedTypes = await generateTypes(schema)

    // Write to file
    const outputPath = join(nitro.options.buildDir, 'types', 'graphql-types.generated.ts')
    const typesDir = join(nitro.options.buildDir, 'types')
    await mkdir(typesDir, { recursive: true })
    await writeFile(outputPath, generatedTypes)

    // Update graphql.d.ts
    const graphqlDtsPath = join(typesDir, 'graphql.d.ts')
    const graphqlDtsContent = `// Auto-generated by nitro-graphql-yoga
import type { Resolvers as Test } from './graphql-types.generated'

declare module 'nitro-graphql-yoga' {
  interface Resolvers extends Test {}
}
`
    await writeFile(graphqlDtsPath, graphqlDtsContent)

    consola.success('[graphql] ✨ Types updated')
  }
  catch (error) {
    consola.error('[graphql] ❌ Type generation failed:', error.message)
  }
}

export async function setupGraphQLWatcher(nitro: Nitro) {
  // Use chokidar directly for reliable file watching
  const watchPatterns = nitro.options.scanDirs.flatMap(dir => [
    join(dir, 'graphql', '**/*.graphql'),
    join(dir, 'graphql', '**/*.gql'),
    join(dir, 'graphql', '**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}'),
  ])

  consola.info('[graphql] 🔧 Setting up file watcher...')

  // Create debounced function for type generation
  const generateTypesDebounced = debounce(async () => {
    consola.start('[graphql] 🔄 Regenerating types...')
    await regenerateGraphQLTypes(nitro)
  }, 300)

  // Use chokidar for reliable file watching with specific files
  const { watch } = await import('chokidar')

  // Watch specific existing files instead of patterns for better reliability
  const existingFiles = await Promise.all(nitro.options.scanDirs.map(async (scanDir) => {
    const { globby } = await import('globby')
    const graphqlDir = join(scanDir, 'graphql')
    return globby([
      join(graphqlDir, '**/*.graphql'),
      join(graphqlDir, '**/*.gql'),
      join(graphqlDir, '**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}'),
    ], { absolute: true })
  })).then(results => results.flat())

  if (existingFiles.length > 0) {
    consola.info(`[graphql] 📁 Watching ${existingFiles.length} files`)
  }
  else {
    consola.warn('[graphql] ⚠️  No files found to watch')
  }

  const watcher = watch(existingFiles.length > 0 ? existingFiles : watchPatterns, {
    persistent: true,
    ignoreInitial: true,
    ignored: /(^|[/\\])\../, // ignore dotfiles
    followSymlinks: false,
    depth: 10,
    usePolling: true, // Enable polling for better compatibility
    interval: 1000, // Check every second
    binaryInterval: 1000,
  })

  watcher.on('ready', () => {
    consola.ready('[graphql] 👁️  Watcher ready')
  })

  watcher.on('change', (path) => {
    const fileName = path.split('/').pop()
    consola.info(`[graphql] 📝 Changed: ${fileName}`)
    generateTypesDebounced()
  })

  watcher.on('add', (path) => {
    const fileName = path.split('/').pop()
    consola.info(`[graphql] ➕ Added: ${fileName}`)
    generateTypesDebounced()
  })

  watcher.on('unlink', (path) => {
    const fileName = path.split('/').pop()
    consola.info(`[graphql] ➖ Removed: ${fileName}`)
    generateTypesDebounced()
  })

  watcher.on('error', (error) => {
    consola.error('[graphql] ❌ Watcher error:', error.message)
  })

  // Hook into Nitro's lifecycle to clean up watcher
  nitro.hooks.hook('close', () => {
    consola.info('[graphql] 🔒 Closing watcher')
    watcher.close()
  })

  // Also try to hook into Nitro's dev:reload for additional triggering
  nitro.hooks.hook('dev:reload', () => {
    generateTypesDebounced()
  })

  consola.success('[graphql] ✅ Watcher ready')
}
